version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: praca_inz
      POSTGRES_USER: MW
      POSTGRES_PASSWORD: MWpassword
    ports:
      - "5433:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg:
